#BERT-SST2-Base

train_input:
    data_processor: "BertCSVRegressionDataProcessor"
    data_dir: "/ocean/projects/sys890003p/spagaria/project1/dana/regression_density"
    vocab_file: "/ocean/projects/sys890003p/spagaria/project1/dana/tokenizer/materials_string_OCELOT.txt"
    max_sequence_length: 512
    batch_size: 16
    shuffle: True
    shuffle_seed: 1
    num_workers: 8
    do_lower: True

eval_input:
    data_processor: "BertCSVRegressionDataProcessor"
    data_dir: "/ocean/projects/sys890003p/spagaria/project1/dana/regression_density"
    vocab_file: "/ocean/projects/sys890003p/spagaria/project1/dana/tokenizer/materials_string_OCELOT.txt"
    max_sequence_length: 512
    batch_size: 16
    shuffle: False
    shuffle_seed: 1
    num_workers: 1
    do_lower: True

model:
    mixed_precision: False
    vocab_size: 52000 
    hidden_size: 768
    num_hidden_layers: 12
    num_heads: 12
    filter_size: 3072
    encoder_nonlinearity: "gelu" # {"gelu", "relu", "silu", "gelu_new"}
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    task_dropout: 0.1
    problem_type: "regression"
    num_labels: 1
    compute_eval_metrics: True

optimizer:
    optimizer_type: "AdamW"
    weight_decay_rate: 0.01
    epsilon: 1e-6
    max_gradient_norm: 1.0
    learning_rate:
        - scheduler: "Linear"
          steps: 2000
          initial_learning_rate: 0.0
          end_learning_rate: 0.00001
        - scheduler: "Constant"
          learning_rate: 0.00001
    loss_scaling_factor: "dynamic"
    log_summaries: True

runconfig:
    # max_steps: 15000  #~25 epochs for the training set # ~3 epochs, 67k samples in an epoch
    max_steps: 3000
    log_steps: 1
    save_summary_steps: 3000
    checkpoint_steps: 3000
    seed: 1
    show_debug_metrics: False
    save_losses: True
    model_dir: "./model_dir"
    save_initial_checkpoint: True
    dist_addr: 'localhost:12355'
