# RoBERTa-Base, MSL:512
# changing batch size, lr, 1000 steps for each run.
# next token prediction accuracy

train_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    #data_dir: "/local1/cerebras/data/openwebtext/owt_bert_pt/train_cased_msl512_mlm_only_unmasked/"
    data_dir: './trial3/csvs/train'
#    vocab_file: "../../vocab/google_research_cased_L-12_H-768_A-12.txt"
    vocab_file: './tokenizer/slices_vocab_OCELOT.txt'
    max_sequence_length: 512
    max_predictions_per_seq: 80
    shuffle: True
    shuffle_seed: 1
    do_lower: False
    # batch_size: 256 # for GPU(16GB) set batch_size: 8
                    # 8 * 32 = 256 with grad_accum_steps: 32
    batch_size: 128 #for trial run
    num_workers: 2

eval_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "./trial3/csvs/val"
    vocab_file: "./tokenizer/slices_vocab_OCELOT.txt"
    max_sequence_length: 512
    max_predictions_per_seq: 80
    shuffle: False
    shuffle_seed: 1 # also for deterministic masking
    do_lower: False
    # batch_size: 256 # for GPU(16GB) set batch_size: 8
    batch_size: 128 #for trial run
    num_workers: 3

test_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "./trial3/csvs/test"
    vocab_file: "./tokenizer/slices_vocab_OCELOT.txt"
    max_sequence_length: 512
    max_predictions_per_seq: 80
    shuffle: False
    do_lower: False
    batch_size: 128
    num_workers: 2


model:
    disable_nsp: True  # turn off NSP head
    # vocab_size: 52000
    vocab_size: 30522 # for BERT-Base, BERT-Large, RoBERTa-Base, RoBERTa-Large
    hidden_size: 768
    num_hidden_layers: 12
    num_heads: 12
    filter_size: 3072
    encoder_nonlinearity: "gelu" # {"gelu", "relu", "silu", "gelu_new"}
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    mlm_loss_weight: 0.019 # should be 0.058 if training with max seq length 128, 0.019 with 512
    layer_norm_epsilon: 1.0e-5
    mixed_precision: True
    compute_eval_metrics: True

optimizer:
    optimizer_type: "AdamW"
    correct_bias: True    
    weight_decay_rate: 0.01
    disable_lr_steps_reset: True
    learning_rate:
       - scheduler: "Linear"
         initial_learning_rate: 0.0
         end_learning_rate: 0.0001
         steps: 10000
       - scheduler: "Linear"
         initial_learning_rate: 0.0001
         end_learning_rate: 0.0
         steps: 1000000  
    loss_scaling_factor: "dynamic"
    max_gradient_norm: 1.0
#    grad_accum_steps: 32 # helps fit in GPU memory

runconfig:
    #num_epochs: 1
    # max_steps: 20000
    max_steps: 5000
    log_steps: 1
    checkpoint_steps: 100 

    seed: 1
    show_debug_metrics: False
    save_losses: True
    save_initial_checkpoint: True

    eval_steps: 6